CREATE TABLE IF NOT EXISTS public.packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
  destination text NOT NULL CHECK (char_length(destination) BETWEEN 1 AND 80),
  budget integer NOT NULL CHECK (budget BETWEEN 1 AND 10000000),
  days text NOT NULL CHECK (char_length(days) BETWEEN 1 AND 100),
  highlights text NOT NULL DEFAULT '',
  type text NOT NULL,
  image text NOT NULL DEFAULT '🧳',
  img text NOT NULL DEFAULT '',
  image_path text,
  rating numeric(2, 1) NOT NULL DEFAULT 4.5,
  reviews integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('travel-photos', 'travel-photos', true, 8388608, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Public can view travel photos" ON storage.objects;
CREATE POLICY "Public can view travel photos"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'travel-photos');